# Dependabot will run on day 23 of each month at 02:38 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "38 2 23 * *"
    open-pull-requests-limit: 20
    assignees:
      - "raschy"
    versioning-strategy: "increase"
